"""
This module is auto generated by azure-ml-component.

Assets included:
    - file:../../../../../components/get-started/**/*.yaml
"""
# THIS IS AN AUTO GENERATED FILE.
# PLEASE DO NOT MODIFY MANUALLY.
from ._assets import (
    microsoft_com_azureml_samples_compare_2_models,
    samples_evaluate,
    samples_mpi_train,
    samples_score,
    samples_train,
)

_assets_spec = [
    'file:../../../../../components/get-started/**/*.yaml',
]

__all__ = [
    'microsoft_com_azureml_samples_compare_2_models',
    'samples_evaluate',
    'samples_mpi_train',
    'samples_score',
    'samples_train',
]