"""
This module is auto generated by azure-ml-component.

Assets included:
    - file:../../../../../components/dummy_pipeline/**/*.yaml
"""
# THIS IS AN AUTO GENERATED FILE.
# PLEASE DO NOT MODIFY MANUALLY.
from ._assets import (
    data_process,
)

_assets_spec = [
    'file:../../../../../components/dummy_pipeline/**/*.yaml',
]

__all__ = [
    'data_process',
]